import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class UserService {

  private products = [
    {
      id: 1,
      name: "Perodua Myvi",
      desc: "The Perodua Myvi is one of the best-selling cars in the Malaysian market, and there are numerous reasons for that. I recently bought the car and I can say it offers the heights of practicality, efficiency, and affordability. With a spacious cabin and great ease of driving the Myvi feels good and looks even better. The driving experience is also exceptional with an efficient and capable engine that offers decent power delivery. The handling is smooth with great driving dynamics and a car is a perfect option for people who need an economical package at its price.",
      imgPath: "https://imgcdn.zigwheels.my/medium/gallery/color/18/1340/perodua-myvi-color-797792.jpg",
      variance: [
        {info: "1.5L AV", price: 58800},
        {info: "1.5L H", price: 53900},
        {info: "1.5L X", price: 49900},
        {info: "1.3L G", price: 47700},
        {info: "1.3L G (No PSDA)", price: 45700},
      ]
    },
    {
      id: 2,
      name: "Proton Saga",
      desc: "The Proton Saga is a very realistic and practical sedan that comes at a reasonable price. I bought the car a few months ago and I really feel that it is a great package at its price. The car is powered by a very capable and fuel efficient 1.3-litre 4-cylinder VVT engine making adequate power for a great driving experience. The car gets fabric upholstery and a range of tech and safety features that makes it a complete and all-inclusive package at a great price.",
      imgPath: "https://assets.autobuzz.my/wp-content/uploads/2015/08/23194948/2015-Proton-Saga-Plus-2.jpg",
      variance: [
        {info: "1.3L Standard MT", price: 32800},
        {info: "1.3L Standard AT", price: 35800},
        {info: "1.3L Premium AT", price: 39800},
      ]
    },
    {
      id: 3,
      name: "Proton X50",
      desc: "The Proton X50 is the flagship model of Proton, and it surely shows that they have put a lot of effort into making this car as feature-packed as possible. I was looking forward to this model for some time as the first car for my son. This particular vehicle ticked all the boxes that a youngster would want from a car and also what their dad would want from the car. Standard safety features along with stylish interior and exterior design and touchscreen console, entertainment system, not to mention the price tag is also conservatively low. This car is definitely a brilliant choice for youngsters and young people at heart. Super impressed with this vehicle. I would highly recommend it.",
      imgPath: "https://cdn.store-assets.com/s/177959/i/19665097.jpg?width=1024",
      variance: [
        {info: "1.5T Standard", price: 79200},
        {info: "1.5T Executive", price: 84800},
        {info: "1.5T Premium", price: 93200},
        {info: "1.5T TGDI Flagship", price: 103300},
      ]
    },
    {
      id: 4,
      name: "Perodua Bezza",
      desc: "The Perodua Bezza is an affordable ride that offers pretty convincing features. I have been driving this vehicle for over a year now. It offers impressive mileage along with dazzling looks. The power generated by the engine is average. However, the looks and the comfortable riding experience make up for the power. The front cockpit and the rear seats are quite spacious so that the passengers have no problem in covering long-distance trips. Bezza can be used conveniently for long-distance trips because of the sheer comfort provided by it. It satisfies all the needs of car lovers. I would recommend this car to all those individuals who want to purchase an affordable ride with decent features.",
      imgPath: "https://images.wapcar.my/file1/429a44a189ff4e33966b53f4896c0444_750x420.jpg",
      variance: [
        {info: "1.3 AV", price: 48356},
        {info: "1.3 X", price: 42551},
        {info: "1.0 G (Auto)", price: 35391},
        {info: "1.0 G (Manual)", price: 33456},
      ]
    },
    {
      id: 5,
      name: "Proton Iriz",
      desc: "Proton Iriz looks smart and unique from the front, and those reflector halogen headlamps act as add ons to enhance its looks. After using it for a while, I can say that it might look small, but the performance is precisely the opposite of its size. The car is a perfect urban hatchback with compact dimensions. It not just looks smart but is feature-rich too. With peppy performance and cutesy styling, Iriz gives perfect competition to its competitors.",
      imgPath: "https://images.wapcar.my/file1/94fa2fadb28d4f188229c78e2ff7ef44_750x420.jpg",
      variance: [
        {info: "1.3L Standard CVT", price: 40800},
        {info: "1.6L Executive CVT", price: 47800},
        {info: "1.6L Active CVT", price: 54800},
      ]
    },
  ]

  getProducts(){
    return this.products;
  }

  getProduct(id: number){
    for (const product of this.products) {
      if(product.id == id){
        return product;
      }
    }
    return null;
  }
}